version: '3'
services:
  web:
    image: nginx:1.8
    restart: always
    ports:
      - "8090:80"
      - "443:443"
    volumes:
      - ./code:/code
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network

  php:
    build: .
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./code:/code
    networks:
      - code-network

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=search_location
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    networks:
      code-network:
        aliases:
          - db.mysql

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "32022:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=123456
    networks:
      - code-network

networks:
  code-network:
    driver: bridge